name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Desplegar al hacer push a la rama main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure SSH
        run: |
          echo "${{ secrets.EC2_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: Add EC2 host to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 98.81.235.62 >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          # Limpiar la carpeta en EC2
          ssh -i private_key.pem ec2-user@98.81.235.62 "rm -rf ~/paginaweb && mkdir ~/paginaweb"
          
          # Copiar los archivos al servidor EC2
          scp -i private_key.pem -r ./* ec2-user@98.81.235.62:~/paginaweb/
          
          # Matar el proceso si ya está usando el puerto 8080
          ssh -i private_key.pem ec2-user@98.81.235.62 "sudo fuser -k 8080/tcp || true"

      - name: Start HTTP server on EC2
        run: |
          # Usar tmux para ejecutar el servidor HTTP en segundo plano
          ssh -i private_key.pem ec2-user@98.81.235.62 << 'EOF'
            # Instalar tmux si no está instalado
            if ! command -v tmux &> /dev/null; then
              sudo yum install -y tmux
            fi
            # Iniciar un nuevo tmux session y ejecutar el servidor HTTP
            tmux new-session -d -s web_server "cd ~/paginaweb && python3 -m http.server 8080"
          EOF
